### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by xurble** [Onaeem26/CubicBezierCurveSwift#1]
Hi, 

Is this code usable by people in their own projects? I found it via your blog which is written like a tutorial, but there's no license in the project and copyright at the top of the files is "All rights reserved"

Is it OK to use this?

**Comment by Onaeem26** [comment]
Hi,
Yes, go ahead and use it. TOTALLY OK to use this code.

Regards,

**Comment by xurble** [comment]
That's brilliant, thank you. The code is amazing and way beyond what my terrible grasp of maths would allow!

I've integrated into a chart library I've been using and the charts are so much better now.
